### PR TITLE
locale updates

### PR DESCRIPTION
**Pull request by jobisoft**

### CODE REVIEW

**Comment by RealRaven2000** [comment]
something seems wrong with the last set lots of locales without change
count (0) e.g. Polish I need to check whether these are splash screen only
at the moment...

**Comment by jobisoft** [comment]
I cannot not compute that statement. Polish has lots of changes:
https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-f056fd341947147dd35f083be41985447311a9def5660cbaab4b8e62f39aa764

And there is not a single file with 0 changes.

**Comment by RealRaven2000** [comment]
cool. I am still on mobile phone and got the summary in an email maybe I
read it wrong?

File Changes

   - *M* _locales/cs/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-a7837875c0566c1f3fda9902bd3f351a7e98e4d5b64e133305de1a2006be26a3>
    (1736)
   - *M* _locales/de/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-537dd75b6b02ee0cbf11183aab34b9842f47db0f5b7fea2a82174860150836e5>
    (1756)
   - *M* _locales/en/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-4362c7f7032e9687a0a5910cadc127afbe8259b2b941de40dd4246c35b1446f0>
    (1754)
   - *M* _locales/es/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-32ced695357ae660fa0743dc36fae7d7397554e7258578a2908e183b8ba51b2a>
    (1754)
   - *M* _locales/fi/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-ae95802753d859373c3aef57cbac845afda61f654b7831be8614e9d84ff8d44e>
    (1754)
   - *M* _locales/fr/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-4fee12151ea49a5007142ae55129100fd236810c59ca5430e407ed62e49f289a>
    (1754)
   - *A* _locales/id-ID/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-d78201a5417fe50a303536954be2bc23aa2a0fba5e4321bdd914d8714946a70b>
    (1379)
   - *M* _locales/it/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-8626d65bbdc4dc22689349ed5390786953c10ed658a5dff219d23cd974275ce5>
    (1755)
   - *M* _locales/ja/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-b5e3c11304a2d336bdee0305184d5e2be2268a098d65f9b388fece9651589c8c>
    (1754)
   - *M* _locales/nl/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-77c66c26e7e4a73dbd6029286dc7e08ad71e840c7e3bc75d662d67facb25d988>
    (1754)
   - *A* _locales/oc/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-c0f4fc875fab09d383f1bb182952b411bbbb4e63927caab5f6b86d115c66b345>
    (1379)
   - *M* _locales/pl/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-f056fd341947147dd35f083be41985447311a9def5660cbaab4b8e62f39aa764>
    (0)
   - *A* _locales/pt-BR/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-d143734f55bfa8e7523cfcc7e7e97679e2432687441c1c83ed62668b0da900dc>
    (0)
   - *M* _locales/ru/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-de4eaeda5a816db4db8babaa76943aaff02520371170bd5d08fbfb33f446783a>
    (0)
   - *M* _locales/sl/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-0f4b2da1475b88c9e995e0239df012ed784c25017f6eb545da58068209216175>
    (0)
   - *M* _locales/sr/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-3a27e742a167bbf0491b8fd7e02009e488208a0506c92ca0c2ae5528039c045a>
    (0)
   - *M* _locales/sv/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-e6e81905eb29bb7fe78a084ffb18c548d7f7f84b80b2a553990dc233d84dae7f>
    (0)
   - *A* _locales/uk/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-a157f5afd53a87fc3bbb4c8c0e326ed512ea5c451291891782a9c24dbce31630>
    (0)
   - *M* _locales/zh-CN/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-59d74216b54fc470c766712a508cdc329ee1a4a6433239bbc0154a405445388d>
    (0)
   - *M* _locales/zh-TW/messages.json
   <https://github.com/RealRaven2000/SmartTemplate4/pull/131/files#diff-314df57055fe02d235f058b12bdefc696b1b18fd80b1af6f0c453b23cee00cbe>
    (0)

**Comment by jobisoft** [comment]
That looks wrong, like if the change is too big, so he does not compute the diff per default. He does the same thing online: you have to click on "show diff" to actually see it.

**Comment by RealRaven2000** [comment]
> That looks wrong, like if the change is too big, so he does not compute the diff per default. He does the same thing online: you have to click on "show diff" to actually see it.

yeah obviously a mistake - I didn't have a way to check from my mobile phone = sorry for the false alarm!

**Pull request merged**
