### PR TITLE
fix for issue #77

### LINKED ISSUE #77: %file()% path truncated at front by 1 letter on Mac OS
The first letter of a  %file()% fileName path is cut off on Mac.

Example: %file(st5.html)% tried to include the file t5.html. Currently the only workaround is to add a "padding" character before the file path name.

### PR DESCRIPTION
**Pull request by hauber**
Please have a look a this suggested fix #77

### CODE REVIEW

**Comment by RealRaven2000** [comment]
Great, I will merge, if you tested it successfully on Mac

**Comment by RealRaven2000** [comment]
hmm, I merged but it's a huge change set. Can you revert and keep my spaces? Sorry it's mixed tabs + spaced; my tabs are 2 spaces wide.

**Comment by RealRaven2000** [comment]
(really don't know why github is such a retard about this)

**Comment by hauber** [comment]
Es sieht so aus, als wäre der Merge nicht vollständig (erste Zeile in content/smartTemplate-util.js).

Die Änderung ist in content/smartTemplate-util.js:1407

   if (filePath && newPath) {
       let relativeFilePath = filePath.substr(path[0] == slash ? 1 : 0) // strip leading slash
       appendedPath = relativeFilePath.replace(noSlash, slash)
   }

**Comment by RealRaven2000** [comment]
are you sure about that line number?; based on 
https://github.com/RealRaven2000/SmartTemplate4/blob/master/content/smartTemplate-util.js#L1407
this would be within the function `isFilePathAbsolute()`

**Pull request merged**
