### PR TITLE
Esr78 add conditional text depending on forward mode

### PR DESCRIPTION
**Pull request by conductor111**
Hello Axel!

I've been using your add-on for a long time. Thank you for your work!

But I was always missing one function: inserting different text in ForwardAsAttachment and ForwardInline modes.
So, there is my solution: I've added a variable-function customTextDependingOnForwardMode, its prototype:
`
%customTextDependingOnForwardMode("forwardInlineModeText", "forwardAsAttachmentModeText")%`

This function allows me to do the following:

**Quote Header:**

```
Hello.

%customTextDependingOnForwardMode("", "The attachment is the forwarded message.")%
```

**Template:**

```
%customTextDependingOnForwardMode("------------------------------------------", "")%
-- 
Best regards,
 Artem Semenov               mailto:artem.semenov@jarillolabs.com
```

And as a result:

**(ForwardAsAttachment mode)**

```
Hello.

The attachment is the forwarded message.

-- 
Best regards,
 Artem Semenov               mailto:artem.semenov@jarillolabs.com
```

**(ForwardInline mode)**

```
Hello.



-------- Forwarded Message --------
Date: 	Sat, 28 Nov 2020 20:00:39 +0300
From: 	test <test@jarillolabs.com>


Some text.


------------------------------------------
-- 
Best regards,
 Artem Semenov               mailto:artem.semenov@jarillolabs.com
```

In addition, I've added a script to build your add-on in the bash shell.

I've tested the changes I made in Thunderbird 78.5.0

Best regards,
 Artem Semenov

### CODE REVIEW

**Comment by RealRaven2000** [comment]
I think this could be improved and made more universal. The function is extremely specialized (which also leads to the long function name) - and the pattern of conditional text [based on different inputs] was requested before - but not based on forwarding mode. Can you rewrite the function to work like this:

`%conditionalText(forwardingMode,"text1","text2")%`

this way we can add more functionality later based on this pattern. The first argument will be extendable for adding different conditions without adding lots of different super specialised functions. In addTokens we would only need to add the string `conditionalText` once and could add more functionality later without functional sprawl. I could also potentially imagine use cases with more than 2 different text arguments following the first "switching" parameter.

**Comment by RealRaven2000** [comment]
Can you do the suggested changes before I merge, or should I merge and modify after the fact? I would really like to be able to extend that `conditionalText` feature with more functionality without adding a bunch of tokens...

**Comment by conductor111** [comment]
Sorry for the delay in answering - I just have a somewhat tense situation.

Of course, I will change my code before merging. Just two questions:

1. What are your rules about variable value names? For forwardMode values:

`'ForwardInline', 'ForwardAsAttachment' `

or just:

`'Inline', 'AsAttachment' `

2. I noticed that both spaces and tabs are used as indents in source code files. What should I use with a future merge in mind?

**Comment by RealRaven2000** [comment]
> Sorry for the delay in answering - I just have a somewhat tense situation.
> 
> Of course, I will change my code before merging. Just two questions:
> 
> 1. What are your rules about variable value names? For forwardMode values:

No, I thought we just use the actual term "`forwardMode`" as the fixed value in 1st parameter (with 2nd parameter being the string for inline case (the default) and 3rd parameter the string for the attachment case). No need to spell out the 2 options, they would just be implicit by using `forwardMode`. As naming goes, I generally like camel case if we have to use more than one word, otherwise all lowercase.

So really you can take everything (up to the string parameters) as literals:

`%conditionalText(forwardMode,"text1","text2")%`

We will probably add more keywords (apart from forwardMode) at a later stage for other conditionals. We will just make a switch based on the first parameter. I have to root around in my support mails for some other examples, I bet I can find a few if I look hard enough.
 
> 2. I noticed that both spaces and tabs are used as indents in source code files. What should I use with a future merge in mind?

Yeah it's bit of a mess (my tab size is 2) I just couldn't convince myself to convert them all to space, but using spaces for anything new would probably be the safest bet.

**Comment by conductor111** [comment]
Sorry, I didn't realize at first that forwardMode is suggested as a fixed value (not as a variable name) to indicate the mode. Now I quite understand your idea. Will do.

**Comment by conductor111** [comment]
Done.

**Comment by conductor111** [comment]
Done.

**Comment by conductor111** [comment]
I'm glad to see this merge. It means that time wasn't wasted. I am ready to continue participating in the project if necessary.

**Comment by RealRaven2000** [comment]
I just uploaded 3.2 - latest release including your new function - can you contact me off github so I can send you a pro license? The new function will be mainly for premium users and you're definitely eligible for a free complimentary license for this!!

**Pull request merged**
